travis:
  secure:
    BINSTAR_TOKEN: owXPOGC1M6dF7Hna+hQ8kzsteLwDheX4xd5lC7x0l3NBnLXbrfgMzTJs+40xsCGgZeYAd5dHL++V62PZW8Ti3b8nf9Hp4EPwzr3Dh4qfqydHHRvgBC1/ao+6FcJPtyKsuFqiZa2pTYgkB2aD2R65kQXyDJmUTkoOIGAN7P7E/IkB6siqS7cY/s69RSu09lJqBWrwv8rY1c9Iezm1yotLSns0HJw48lwtM1y5PqdizccK5ZB6NrzLdx1hM02r5yJZ1zZ15ePYSENojKjDxlTY6S+cl/oi39zPnEyYZL74oVAaG3KtCkttUrYkpRb3Gtc8bTQXbSu71/Y8Emw+SlFs2vshM3PiWeCJGi1y3ErRC2arba622VFIBP3nCJuFdgrNk2b5nMOWo++E92EWhtHUj8FvA6Yx/i/Bh8SVhnY2BVMeM2H8tsMDRujNbeFAKCvrcbHk4bsI1PyBdb9Q/5Y7vaqEROKoGlwfVouy3HWMzO3/XHbgwb81RE2fQGa/WDzKwZpOMVTiTlaSpfWRH2wlGBkp97HaTqBLt/jFiEu8qQVG2ab1l8G81hna0VZndnMb04iKtbKy/rbKg1I0f8mBDeKafRhParsGFo8pTehSIarztoOWWUUG+WgTO5PK6sQjX57vg4s/dTKA9nuXTkSlAX42r4blyo0YOYW69TetRSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
